export const POPULAR = {
    SET_LANGUAGE: 'POPULAR.SET_LANGUAGE',
    FILTER_REPOS: 'POPULAR.FILTER_REPOS',
    GET_REPOS_LOADING: 'POPULAR.GET_REPOS_LOADING',
    GET_REPOS_FAILURE: 'POPULAR.GET_REPOS_FAILURE',
    GET_REPOS_SUCCESS: 'POPULAR.GET_REPOS_SUCCESS',
};